#!/usr/bin/env sh

env_file=.env.local

if [ -f "$env_file" ]; then
    sender_id=$(cat "$env_file" | grep SENDER_ID | awk -F'=' '{print $2}');

    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        sed -i "s/<%= SENDER_ID %>/$sender_id/g" dist/firebase-messaging-sw.js
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        if command -v gsed > /dev/null; then
            gsed -i "s/<%= SENDER_ID %>/$sender_id/g" dist/firebase-messaging-sw.js
        else
            echo "Install gsed first: brew install gsed.";
        fi;
    else
        echo "OS not supported: not macOS or Linux".;
    fi;
else 
    echo "Cannot set sender ID: $env_file does not exist.";
fi;
